namespace SR2MP.Packets.Utils;

public enum PacketType : byte
{   // Type                       // Hierarchy                                    // Frequency                          // Use Case
    None = 0,                     // Both Ways                                    Unused                                Empty packet data, exists for convention purposes and default none value
    Connect = 1,                  // Client -> Server                             Low (manual)                          Try to connect to Server
    ConnectionApprove = 2,        // Server -> Client                             Low (depends on connect)              Initiate Player Join
    ConnectionDeny = 3,           // Server -> Client                             Low (can be manual)                   On Connection Deny
    Close = 4,                    // Server -> All Clients                        Low (manual)                          Broadcast Server Close
    Heartbeat = 5,                // Client -> Server                             Low (Currently unused)                Check if Clients are alive
    HeartbeatAck = 6,             // Server -> Client                             Low (depends on heartbeat)            Automatically time the Clients out if the Server crashes
    ChatMessage = 7,              // Client -> Server                             Low (manual)                          Chat message
    ResyncRequest = 8,            // Client -> Server                             Low (manual)                          Request a resync from server
    PlayerJoin = 9,               // Client -> Server                             Low (manual)                          Join a World
    BroadcastPlayerJoin = 10,     // Server -> All Clients                        Low (depends on join)                 Add Player on other Clients
    PlayerLeave = 11,             // Client -> Server                             Low (manual)                          Leave a World
    BroadcastPlayerLeave = 12,    // Server -> All Clients                        Low (depends on leave)                Remove Player on other Clients
    PlayerUpdate = 13,            // Client -> Server                             Very High                             Update Player
    PlayerFX = 14,                // Both Ways                                    Medium (manual)                       On Player FX
    MovementSound = 15,           // Both Ways                                    Medium (manual)                       On Movement SoundPlay
    PlayerGadgetUpdate = 16,      // Both Ways                                    Very High (depends on player mode)    Gadget Mode toggle
    InitialPlayerUpgrades = 17,   // Server -> Client                             Low                                   Player Upgrades on Load
    PlayerUpgrade = 18,           // Both Ways                                    Low (manual)                          On Upgrade
    ActorSpawn = 19,              // Both Ways                                    High (can be manual)                  On Actor Spawn
    ActorDestroy = 20,            // Both Ways                                    High (can be manual)                  On Actor Destroy
    ActorUpdate = 21,             // Both Ways                                    Very High                             On Actor Update
    ActorTransfer = 22,           // Both Ways                                    High (can be manual)                  On Actor Transfer
    ActorUnload = 23,             // Both Ways                                    High                                  On Actor unloaded
    InitialActors = 24,           // Server -> Client                             Low                                   Actors on Load
    ResourceAttach = 25,          // Both Ways                                    Very High                             On Resource Attach
    WorldTime = 26,               // Server -> All Clients                        Very High (depends on join too)       Updates Time
    FastForward = 27,             // Client -> Server                             Medium (can be manual)                On Sleep & Death
    WorldFX = 28,                 // Both Ways                                    High                                  On World FX
    CurrencyAdjust = 29,          // Both Ways                                    High (can be manual)                  On Plort sell
    MarketPriceChange = 30,       // Both Ways                                    Medium                                On Plort Market Price Change
    WeatherUpdate = 31,           // Server -> All Clients                        High                                  On Weather Update
    InitialWeather = 32,          // Server -> Client                             Low (depends on join)                 Weather on Load
    LightningStrike = 33,         // Both Ways                                    Low                                   On Lightning Strike
    NewLandPlot = 34,             // Both Ways                                    Low (manual)                          New land plot set
    LandPlotUpgrade = 35,         // Both Ways                                    Low (manual)                          Land plot upgrade
    InitialLandPlots = 36,        // Server -> Client                             Low                                   Plots on Load
    GardenPlant = 37,             // Both Ways                                    Medium (manual)                       On Food Planted
    GardenUpdate = 38,            // Both Ways                                    High                                  On Garden update
    GardenOwnership = 39,         // Both Ways                                    Medium (manual)                       On Garden ownership transfer
    AutoFeederSpeed = 40,         // Both Ways                                    Low (manual)                          On Auto Feeder speed switch
    AutoFeederDispense = 41,      // Both Ways                                    Medium                                On Auto Feeder food dispense
    PlortCollection = 42,         // Both Ways                                    Medium (can be manual)                On Plorts collected
    GordoFeed = 43,               // Both Ways                                    Medium (manual)                       On Gordo Fed
    GordoBurst = 44,              // Both Ways                                    Low (depends on feed)                 On Gordo Burst
    InitialGordos = 45,           // Server -> Client                             Low (depends on join)                 Gordos on Load
    SwitchActivate = 46,          // Both Ways                                    Low                                   On Switch Activated
    InitialSwitches = 47,         // Server -> Client                             Low (depends on join)                 Switches on Load
    GeyserTrigger = 48,           // Both Ways                                    High                                  On Geyser Fired
    MapUnlock = 49,               // Both Ways                                    Low                                   On Map unlock
    InitialMapEntries = 50,       // Server -> Client                             Low (depends on join)                 Map on Load
    AccessDoor = 51,              // Both Ways                                    Low                                   On Map Extension bought
    InitialAccessDoors = 52,      // Server -> Client                             Low (depends on join)                 Access Doors on Load
    TreasurePod = 53,             // Both Ways                                    Medium (manual)                       On Treasure Pod open
    InitialTreasurePods = 54,     // Server -> Client                             Low (depends on join)                 Treasure Pods on join
    AmmoIncrement = 55,
    AmmoAdd = 56,
    AmmoAddToSlot = 57,
    AmmoDecrement = 58,
    AmmoDecrementSelected = 59,
    SiloSlotSelect = 60,          // Both Ways                                    Medium (manual)                       On Silo Slot Switch
    RefineryUpdate = 61,          // Both Ways                                    Medium (can be manual)                On Refinery Change
    InitialRefinery = 62,         // Server -> Client                             Low (depends on join)                 Refinery items on join
    PediaUnlock = 63,             // Both Ways                                    Medium (manual)                       On Pedia entry
    InitialPediaEntries = 64,     // Server -> Client                             Low                                   Pedia Entries on Load
    ModSync = 100,                // Server -> Client                             Low (manual)                          Sync Mod names on incompatible mod
    ModSyncAck = 101,             // Client -> Server                             Low (manual)                          Mod names on incompatible mod
    ApiCall = 253,                // Both Ways                                    Variable                              Backing for mod's api packets
    ReservedAcknowledge = 254,    // Both Ways                                    Very High                             For acknowledge packets
    ReservedCompression = 255     // Both Ways                                    Very High                             For packet compression
}